# Python Basic

In [1]:
import pandas as pd

## 1. Data Type

### a. Int / Float

In [2]:
1 + 3

4

In [3]:
17 / 4

4.25

In [4]:
int(17 / 4), 17 // 4

(4, 4)

In [5]:
17 % 4

1

In [6]:
import math
math.sqrt(9)

3.0

In [7]:
e = math.e
math.log(e)

1.0

In [8]:
math.pow(2, 2), 2**2

(4.0, 4)

In [9]:
type(math.pow(2, 2)), type(2**2)

(float, int)

In [10]:
2.13e2

213.0

In [11]:
print("a = %0.5f, b = %5.0f" % (2018.0728, 2018.0728))

a = 2018.07280, b =  2018

### b. Bool

In [12]:
a = True
b = False

In [13]:
# OR 연산
# Logical OR
a + b, bool(a + b)

(1, True)

In [14]:
# AND 연산
# Logical AND
a*b, bool(a*b)

(0, False)

In [15]:
a == False, b == False

(False, True)

In [16]:
type( 1 != 1 )

bool

### c. String

In [17]:
a = "Hello?"
b = "World!"

In [18]:
type(a)

str

In [19]:
a[0]

'H'

In [20]:
a[1:]

'ello?'

In [21]:
a[-1]

'?'

In [22]:
a + b

'Hello?World!'

In [23]:
a + " " + b

'Hello? World!'

In [24]:
print("a = %s, b = %s" % (a, b))

a = Hello?, b = World!

## 2. IF/WHILE/FOR

### a. If

In [25]:
a = 2

In [26]:
if a == 1 :
    print("a is 1")
elif a==2 :
    print("a is 2")
else :
    print("a is not 1 or 2")

a is 2

### b. While

In [27]:
while a < 5 : 
    a = a + 1
    print(a)

3
4
5

In [28]:
b = 0 
while b < 10:
    b = b + 1
    if b % 2 != 0 :
        continue
    else :
        print(b)

2
4
6
8
10

### c. For

In [29]:
for i in range(0, 10) :
    print(" a > ", i, " : ", a > i )

 a >  0  :  True
 a >  1  :  True
 a >  2  :  True
 a >  3  :  True
 a >  4  :  True
 a >  5  :  False
 a >  6  :  False
 a >  7  :  False
 a >  8  :  False
 a >  9  :  False

In [30]:
for i in range(0, 10, 2) :
    print(i)

0
2
4
6
8

## 3. Collection

### a. List

In [31]:
a = [1, 2, 3]
b = [4, 5, 6]

In [32]:
a + b

[1, 2, 3, 4, 5, 6]

In [33]:
a[0], b[0]

(1, 4)

In [34]:
a.append(4)

In [35]:
a

[1, 2, 3, 4]

In [36]:
del a[2:3]

In [37]:
a

[1, 2, 4]

In [38]:
a*2

[1, 2, 4, 1, 2, 4]

In [39]:
b.index(6)

2

In [40]:
for i, n in enumerate(b) :
    print(i, "th : ", n)

0 th :  4
1 th :  5
2 th :  6

### b. Dictionary

In [41]:
a = {}

In [42]:
a['Greet'] = 'Hello'

In [43]:
a['Response'] = 'Hi'

In [44]:
a.keys()

dict_keys(['Greet', 'Response'])

In [45]:
a.values()

dict_values(['Hello', 'Hi'])

In [46]:
a['Greet']

'Hello'

## 4. Def/Exception/Class

### a. Def

In [47]:
def add2(x) :
    return x + 2

In [48]:
add2(3)

5

In [49]:
add2('HELLO')

TypeError: can only concatenate str (not "int") to str

### b. Exception

In [50]:
def add2(x) :
    try :
        return x + 2
    except TypeError as e :
        print("ERROR occured", e)

In [51]:
add2(3)

5

In [52]:
add2('HELLO')

ERROR occured can only concatenate str (not "int") to str

### c. Class

In [53]:
class A():
    def __init__(self):
        print("Initialization A")
        
    def info(self):
        print("Info of A")

In [54]:
a = A()

Initialization A

In [55]:
a.info()

Info of A

## 5. Data Processing

### a. TXT to String

In [56]:
f = open("./data/sample.txt", 'r')
while True:
    line = f.readline()
    if not line: break
    print(line)
    print("<Enter>")
f.close()

Natural Language Processing (NLP) is a technology that converts unstructured natural language spoken by humans into structured language data understandable by computers. This process enables computers to comprehend the intent of sentences and accurately grasp the speaker's intentions.

<Enter>


<Enter>
In AI services, NLP plays a crucial role. It allows computers to parse natural language into morphemes, the smallest grammatical units, patterning linguistic structures to understand the overall meaning. NLP covers various tasks, including Part-of-Speech (POS) tagging, which resolves ambiguities within grammatical categories, stop-word removal, machine translation, and dialogue systems.

<Enter>


<Enter>
Recently, deep learning-based NLP research has been growing. It has become possible to infer meaning from the entire context of sentences rather than just individual words. To apply deep learning, it's essential to obtain a corpus?linguistic data used for training.

<Enter>


<Enter>
Speech recognition technology based on NLP is rapidly evolving due to advancements in network and computing technologies capable of storing large-scale voice data and processing it in real-time. The core of speech recognition technology is maintaining continuous dialogue with the interlocutor.
<Enter>

In [57]:
f = open("./data/sample.txt", 'r')
lines = f.read()
print(lines)
f.close()

Natural Language Processing (NLP) is a technology that converts unstructured natural language spoken by humans into structured language data understandable by computers. This process enables computers to comprehend the intent of sentences and accurately grasp the speaker's intentions.

In AI services, NLP plays a crucial role. It allows computers to parse natural language into morphemes, the smallest grammatical units, patterning linguistic structures to understand the overall meaning. NLP covers various tasks, including Part-of-Speech (POS) tagging, which resolves ambiguities within grammatical categories, stop-word removal, machine translation, and dialogue systems.

Recently, deep learning-based NLP research has been growing. It has become possible to infer meaning from the entire context of sentences rather than just individual words. To apply deep learning, it's essential to obtain a corpus?linguistic data used for training.

Speech recognition technology based on NLP is rapidly evolving due to advancements in network and computing technologies capable of storing large-scale voice data and processing it in real-time. The core of speech recognition technology is maintaining continuous dialogue with the interlocutor.

### b. EXCEL to Dataframe

# Pandas는 Python 기반의 빠르고 유연한 오픈소스 데이터 분석/조작 라이브러리
# Pandas is a fast, flexible open-source data analysis and manipulation tool in Python

In [58]:
import pandas as pd

In [59]:
xlsx = pd.read_excel('./data/sample.xlsx', sheet_name=0)

In [60]:
xlsx

             Name  Korean  Match
0     Kang Daniel       0     50
1     Kang Dongho       0     50
2       Kang Mina      70     85
3    Kwon Hyunbin      70     85
4      Kim Doyeon      40     70
5      Kim Samuel      90     95
6     Kim Sejeong      80     90
7       Kim Sohye      20     60
8     Kim Chungha      40     70
9     Noh Taehyun       0     50
10    Lai Kuanlin      70     85
11    Park Woojin      20     60
12    Park Jihoon      30     65
13   Bae Jinyoung      80     90
14   Ong Seongwoo      50     75
15   Yoo Yeonjung      40     70
16     Im Nayoung      50     75
17      Jeon Somi      10     55
18  Jung Chaeyeon      10     55
19  Zhou Jieqiong      50     75
20    Ju Haknyeon      50     75
21   Choi Yoojung      70     85
22   Takada Kenta      30     65
23    Ha Sungwoon      10     55

### c. CSV to DataFrame

In [61]:
csv = pd.read_csv('./data/sample.csv', header=0, sep=',', encoding='euc-kr')

In [62]:
csv

             Name  Korean  Math
0     Kang Daniel      10    55
1     Kang Dongho      60    80
2       Kang Mina       0    50
3    Kwon Hyunbin      20    60
4      Kim Doyeon      60    80
5      Kim Samuel      30    65
6     Kim Sejeong      60    80
7       Kim Sohye      60    80
8     Kim Chungha      10    55
9     Noh Taehyun      40    70
10    Lai Kuanlin      70    85
11    Park Woojin      10    55
12    Park Jihoon      30    65
13   Bae Jinyoung       0    50
14   Ong Seongwoo      20    60
15   Yoo Yeonjung      60    80
16     Im Nayoung      90    95
17      Jeon Somi       0    50
18  Jung Chaeyeon       0    50
19  Zhou Jieqiong      90    95
20    Ju Haknyeon      10    55
21   Choi Yoojung      90    95
22   Takada Kenta      60    80
23    Ha Sungwoon      10    55

### d. DataFrame to Numpy

# NumPy는 수치 연산, 선형대수, 난수 생성 등 과학계산 핵심 기능을 제공
# NumPy provides core scientific-computing features like numeric ops, linear algebra, and random sampling

In [63]:
import numpy as np

In [64]:
data = xlsx.values

In [65]:
type(data)

numpy.ndarray

In [66]:
data

array([['Kang Daniel', 0, 50],
       ['Kang Dongho', 0, 50],
       ['Kang Mina', 70, 85],
       ['Kwon Hyunbin', 70, 85],
       ['Kim Doyeon', 40, 70],
       ['Kim Samuel', 90, 95],
       ['Kim Sejeong', 80, 90],
       ['Kim Sohye', 20, 60],
       ['Kim Chungha', 40, 70],
       ['Noh Taehyun', 0, 50],
       ['Lai Kuanlin', 70, 85],
       ['Park Woojin', 20, 60],
       ['Park Jihoon', 30, 65],
       ['Bae Jinyoung', 80, 90],
       ['Ong Seongwoo', 50, 75],
       ['Yoo Yeonjung', 40, 70],
       ['Im Nayoung', 50, 75],
       ['Jeon Somi', 10, 55],
       ['Jung Chaeyeon', 10, 55],
       ['Zhou Jieqiong', 50, 75],
       ['Ju Haknyeon', 50, 75],
       ['Choi Yoojung', 70, 85],
       ['Takada Kenta', 30, 65],
       ['Ha Sungwoon', 10, 55]], dtype=object)

In [67]:
korean_score = data[:, 1]

In [68]:
print("Sum : ", np.sum(korean_score))
print("Mean : ", np.mean(korean_score))
print("Std : ", np.std(korean_score))
print("Max : ", np.max(korean_score))

Sum :  980
Mean :  40.833333333333336
Std :  27.525240941522906
Max :  90